//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstFisica_EstReparo
    {
        public int Id { get; set; }
        public int IdEstFisica { get; set; }
        public int IdEstReparo { get; set; }
    
        public virtual tblEstFisica tblEstFisica { get; set; }
        public virtual tblEstReparo tblEstReparo { get; set; }
    }
}
