//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FiscCaEq
    {
        public int Id { get; set; }
        public int FkFiscalizacao { get; set; }
        public int FkCatSeg { get; set; }
    
        public virtual tblEquipamentosSeg tblEquipamentosSeg { get; set; }
        public virtual tblFiscalizacao tblFiscalizacao { get; set; }
    }
}
