//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gas_OpcaoGas
    {
        public int Id { get; set; }
        public int IdGas { get; set; }
        public int IdOpGas { get; set; }
    
        public virtual tblGasCozinha tblGasCozinha { get; set; }
        public virtual tblOpGas tblOpGas { get; set; }
    }
}
