//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iluminacao_IluReparo
    {
        public int Id { get; set; }
        public int IdIluminacao { get; set; }
        public int IdIluReparo { get; set; }
    
        public virtual tblIluminacao tblIluminacao { get; set; }
        public virtual tblIluReparo tblIluReparo { get; set; }
    }
}
