//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incendio_Extintor
    {
        public int Id { get; set; }
        public int IdIncendio { get; set; }
        public int IdExtintor { get; set; }
    
        public virtual tblExtintor tblExtintor { get; set; }
        public virtual tblSisIncendio tblSisIncendio { get; set; }
    }
}
