//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSase.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaSaseEntities : DbContext
    {
        public SistemaSaseEntities()
            : base("name=SistemaSaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EstFisica_EstReparo> EstFisica_EstReparo { get; set; }
        public virtual DbSet<FiscCaEq> FiscCaEq { get; set; }
        public virtual DbSet<Gas_OpcaoGas> Gas_OpcaoGas { get; set; }
        public virtual DbSet<Iluminacao_IluReparo> Iluminacao_IluReparo { get; set; }
        public virtual DbSet<Incendio_Extintor> Incendio_Extintor { get; set; }
        public virtual DbSet<tblAcessibilidade> tblAcessibilidade { get; set; }
        public virtual DbSet<tblArredoresUeb> tblArredoresUeb { get; set; }
        public virtual DbSet<tblEquipamentosSeg> tblEquipamentosSeg { get; set; }
        public virtual DbSet<tblEstFisica> tblEstFisica { get; set; }
        public virtual DbSet<tblEstReparo> tblEstReparo { get; set; }
        public virtual DbSet<tblExtintor> tblExtintor { get; set; }
        public virtual DbSet<tblFiscalizacao> tblFiscalizacao { get; set; }
        public virtual DbSet<tblGasUeb> tblGasUeb { get; set; }
        public virtual DbSet<tblGestor> tblGestor { get; set; }
        public virtual DbSet<tblIluminacao> tblIluminacao { get; set; }
        public virtual DbSet<tblIluReparo> tblIluReparo { get; set; }
        public virtual DbSet<tblListaTel> tblListaTel { get; set; }
        public virtual DbSet<tblLivroRegistro> tblLivroRegistro { get; set; }
        public virtual DbSet<tblOcoInternas> tblOcoInternas { get; set; }
        public virtual DbSet<tblOpGas> tblOpGas { get; set; }
        public virtual DbSet<tblPanicoIncendio> tblPanicoIncendio { get; set; }
        public virtual DbSet<tblProjViolencia> tblProjViolencia { get; set; }
        public virtual DbSet<tblRegistro> tblRegistro { get; set; }
        public virtual DbSet<tblSisHidraSaniRep> tblSisHidraSaniRep { get; set; }
        public virtual DbSet<tblSisIncendio> tblSisIncendio { get; set; }
        public virtual DbSet<tblTransito> tblTransito { get; set; }
        public virtual DbSet<tblUeb> tblUeb { get; set; }
        public virtual DbSet<tblQntPosto> tblQntPosto { get; set; }
        public virtual DbSet<tblTipoSeg> tblTipoSeg { get; set; }
    }
}
