//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEstFisica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEstFisica()
        {
            this.tblFiscalizacao = new HashSet<tblFiscalizacao>();
        }
    
        public int Id { get; set; }
        public bool Estacionamento { get; set; }
        public bool ControleVeiculos { get; set; }
        public bool PortaoEletronico { get; set; }
        public bool EstaRetrito { get; set; }
        public bool ParaRaios { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFiscalizacao> tblFiscalizacao { get; set; }
    }
}
