//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEquipamentosSeg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEquipamentosSeg()
        {
            this.tblCatSeg = new HashSet<tblCatSeg>();
        }
    
        public int Id { get; set; }
        public bool Fardamento { get; set; }
        public bool Apito { get; set; }
        public bool CapaChuva { get; set; }
        public bool Colete { get; set; }
        public bool Tonfa { get; set; }
        public bool Lanterna { get; set; }
        public bool Cracha { get; set; }
        public bool Quepe { get; set; }
        public bool Revolver { get; set; }
        public bool Radio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCatSeg> tblCatSeg { get; set; }
    }
}
