//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFiscalizacao
    {
        public int Id { get; set; }
        public int FkUeb { get; set; }
        public int FkRegistro { get; set; }
        public int FkLivroRegistro { get; set; }
        public int FkCatSeg { get; set; }
        public int FkEstFisica { get; set; }
        public int FkIluminacao { get; set; }
        public int FkSisHidraSaniRep { get; set; }
        public int FkSisIncendio { get; set; }
        public int FkGasCozinha { get; set; }
        public int FkPanicoIncendio { get; set; }
        public int FkTransito { get; set; }
        public int FkAcessibilidade { get; set; }
        public int FkArredoresUeb { get; set; }
        public int FkProjViolencia { get; set; }
        public int FkListaTel { get; set; }
        public int FkOcoInternas { get; set; }
    
        public virtual tblAcessibilidade tblAcessibilidade { get; set; }
        public virtual tblArredoresUeb tblArredoresUeb { get; set; }
        public virtual tblCatSeg tblCatSeg { get; set; }
        public virtual tblEstFisica tblEstFisica { get; set; }
        public virtual tblRegistro tblRegistro { get; set; }
        public virtual tblUeb tblUeb { get; set; }
        public virtual tblGasCozinha tblGasCozinha { get; set; }
        public virtual tblIluminacao tblIluminacao { get; set; }
        public virtual tblListaTel tblListaTel { get; set; }
        public virtual tblLivroRegistro tblLivroRegistro { get; set; }
        public virtual tblOcoInternas tblOcoInternas { get; set; }
        public virtual tblPanicoIncendio tblPanicoIncendio { get; set; }
        public virtual tblProjViolencia tblProjViolencia { get; set; }
        public virtual tblSisHidraSaniRep tblSisHidraSaniRep { get; set; }
        public virtual tblSisIncendio tblSisIncendio { get; set; }
        public virtual tblTransito tblTransito { get; set; }
    }
}
