//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIluReparo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblIluReparo()
        {
            this.tblIluminacao = new HashSet<tblIluminacao>();
        }
    
        public int Id { get; set; }
        public bool Fiacao { get; set; }
        public bool CaixaForca { get; set; }
        public bool Interruptores { get; set; }
        public bool Tomadas { get; set; }
        public bool ArCon { get; set; }
        public bool Ventilador { get; set; }
        public bool Geladeira { get; set; }
        public bool Frezzer { get; set; }
        public bool Bebedouro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblIluminacao> tblIluminacao { get; set; }
    }
}
