//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTipoSeg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTipoSeg()
        {
            this.tblFiscalizacao = new HashSet<tblFiscalizacao>();
        }
    
        public int Id { get; set; }
        public bool Vigilante { get; set; }
        public bool Porteiro { get; set; }
        public bool VigiFeirista { get; set; }
        public bool PortFeirista { get; set; }
        public bool VigSemedPort { get; set; }
        public bool VigSemed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFiscalizacao> tblFiscalizacao { get; set; }
    }
}
