//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaSase.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUeb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUeb()
        {
            this.tblFiscalizacao = new HashSet<tblFiscalizacao>();
        }
    
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Endereco { get; set; }
        public string Nucleo { get; set; }
        public int FKGestor { get; set; }
        public string Contato { get; set; }
        public string Contato2 { get; set; }
        public System.DateTime DataHora { get; set; }
        public int FkRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFiscalizacao> tblFiscalizacao { get; set; }
        public virtual tblGestor tblGestor { get; set; }
        public virtual tblRegistro tblRegistro { get; set; }
    }
}
